### ISSUE TITLE
Use Lists for storting block/mute lists

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#101]
- [NIP PR](https://github.com/nostr-protocol/nips/pull/114)

Lists can be used to store public or private lists of note ids or pubkeys. The immediate and most important use case is encrypted block/mute lists that are interoperable between clients but we can explore creating lists to follow `e`, `t` and `p` tags in the future.

**Comment by verbiricha** [comment]
Duplicate of https://github.com/v0l/snort/issues/94

**Comment by monlovesmango** [comment]
fyi pr has moved here: https://github.com/nostr-protocol/nips/pull/183
