### ISSUE TITLE
Cannot add relays if none exist in profile

### ISSUE THREAD

**Issue by Fierillo** [v0l/snort#109]
Windows 11 and Android 11

When i try to load my prívate key with all my info and NIP-05 i dont get any event. Go to settings and SEE that i havent any relay. Try to manually add but i can't save, then is deleted automatically. 

This only happens with my prívate key if i generate a new random key all works fine.

**Comment by v0l** [comment]
What is your pubkey

**Comment by v0l** [comment]
I also just pushed some fixes for relays page maybe you can check again and see if it improved

**Comment by Fierillo** [comment]
> What is your pubkey

npub18ggwqfvqmxt3m6f4ek2q55nghlj9380me364wd67wz8yzpyh8wusevpdmh

> I also just pushed some fixes for relays page maybe you can check again and see if it improved

I will to try. Thanks!

**Comment by v0l** [comment]
Your relay list is empty, the changes i pushed earlier should fix this for you 
![image](https://user-images.githubusercontent.com/1172179/213885601-2e4b3c89-5b98-4feb-a1b6-cd5536b57251.png)

**Comment by Fierillo** [comment]
No, is not working, now i can add relays manually but i not receive any note or update, when i refresh the browser all the relays are deleted automatically.

**Comment by v0l** [comment]
Try to clear your browser cache first, it sounds like its doing exactly as before, i have already tested it btw i set my profile to empty relay list then open snort and add realys and save and it works after reload

**Comment by Fierillo** [comment]
how do you set your profile to empty relay list?

**Comment by Fierillo** [comment]
I tried to clear cache, tried with 3 different browsers edge, brave, chrome, also different SO, android and windows 11.

is not working, the problem looks to be my private key

**Comment by Fierillo** [comment]
Now is working! your new update fix the problem! thanks a lot!
