### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#115]
- Notes fade in/out
- Count increase (zaps)
- Timeline change transitions, generic navigation transition

**Comment by v0l** [comment]
Not a fan of transitions honestly, i think it will ruin the snappy feeling, but maybe we just keep them very short?

**Comment by bitcoinuser** [comment]
> Not a fan of nav transitions honestly, i think it will ruin the snappy feeling, but maybe we just keep them very short?

I like animations. What about all these things as optional? So user could change on settings.
