### ISSUE TITLE
If I'm on global feed and new notes appear on Posts feed, I think on Posts feed tab should appear a green dot indicating that there are new notes.

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#122]
Hi,

If I'm on global feed and new notes appear on Posts or Posts & Replies feed, I think on Posts or Posts & Replies feed tab should appear a green dot indicating that there are new notes.

Sometimes I'm following Global feed and I need to switch to other tabs to see if there are new notes. Or I open Snort on two tabs on Browser and I let one on Global feed and the other on Posts Feed. This is a workaround.

**Comment by v0l** [comment]
we dont keep notes around between these tabs, it would be too much data
