### ISSUE TITLE
When I switch tabs and go back to original Posts tab, the videos shouldn't load again. 

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#124]
Hi,

When I switch tabs and go back to original Posts tab, the videos shouldn't load again. See the video:

https://user-images.githubusercontent.com/1178856/213938833-aadd5103-294f-4d15-9402-a06b4dac0bf4.mp4

**Comment by v0l** [comment]
They should load again, we're not keeping all notes hidden in the background that would slow the page down
