### ISSUE TITLE
Add bandchecks in function to follows

### ISSUE THREAD

**Issue by Fierillo** [v0l/snort#134]
I saw this feature in Iris.to and is pretty amaizing.

Green check: You are following this account.
Yellow check: more that 10 friends are following this account.
White check: less than 10 friends are following this account.

![image](https://user-images.githubusercontent.com/31271916/214298751-697e9976-0717-4809-b629-3b84d2196f79.png)

**Comment by v0l** [comment]
I dont think we should add this, everybody should be treated equally

**Comment by v0l** [comment]
And what is the purpose of NIP-05?

**Comment by Fierillo** [comment]
I think the bandchecks are an elegant solution to this problem, the NIP-05 is good also but people can be tricked if they not look carefully.
