### ISSUE TITLE
Some users can't update their avatar

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#150]
Don't have more information unfortunately, but the file doesn't seem to even upload, nothing happens.

**Comment by v0l** [comment]
Cant replicate, working fine here

**Comment by verbiricha** [comment]
Same for me but got two people tell me this today. We can close and discard if nobody else reports problems.

**Comment by verbiricha** [comment]
Ran into this today, image is uploaded but there is an exception in the promise and is interpreted as failed:

<img width="821" alt="Screenshot 2023-01-30 at 09 44 48" src="https://user-images.githubusercontent.com/92299987/215429287-de875435-8cfa-4751-ab10-648bd9dbf43c.png">
<img width="868" alt="Screenshot 2023-01-30 at 09 44 59" src="https://user-images.githubusercontent.com/92299987/215429288-bec2a42b-b166-48f1-99f5-ac19433aacc5.png">

**Comment by v0l** [comment]
Fixed in 462fc60dfef1ec1229000b61adba73efdcb233a0
