### ISSUE TITLE
Can't Update Avatar Image

### ISSUE THREAD

**Issue by pnickdurham** [v0l/snort#173]
Allows for file selection but ultimately the image file is never uploaded. I saw a past issue was closed but I've experienced the same issue.

**Comment by v0l** [comment]
Clear cache and check again

**Comment by pnickdurham** [comment]
Picture uploaded this time but now won't save

**Comment by v0l** [comment]
Not enough info, please provide more details

**Comment by pnickdurham** [comment]
<img width="984" alt="Screen Shot 2023-01-30 at 5 40 33 PM" src="https://user-images.githubusercontent.com/123976391/215612618-3d5587b8-1d7b-41ed-aba0-d2e537ba6ecf.png">

New avatar image uploaded correctly, but when I go to save the changes, the save button doesn't appear functional and I get no confirmation that my changes have been saved. When my feed is refreshed, the original nostrich avatar appears.
