### ISSUE TITLE
UI Minor bug

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#178]
https://user-images.githubusercontent.com/1178856/215720054-c4174a09-d3e1-46af-8951-5e395af3fb4e.mp4

**Comment by ivanacostarubio** [comment]
This happens when a user with a long NIP05 note is on the timeline or profile. 

Ex: https://snort.social/p/npub1gw2veenjhjk0afmha9jslmlksc37svlp2rkagupp3nshdlpx8zfsf4nvxa
