### ISSUE TITLE
Add Spotify embed like on nostrgram

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#182]
Render share link as embedded player. https://open.spotify.com/track/0Kze26iCzT0tap9FtpQqHa?si=51312e491a3a4315 renders like this on nostrgram.

![Screenshot 2023-01-31 at 9 35 15 PM](https://user-images.githubusercontent.com/3655410/215939030-c3ae5163-e98e-46e8-a23d-e556a12c1af1.png)

Snort
https://snort.social/e/note1gqxus8zucm9qvrg3k0r94krl48s8wuhh50n4qxtkeut4zhzv0xfss3m49l

vs

Nostrgram
https://nostrgram.co/#thread:400dc81c5cc6ca060d11b3c65ad87fa9e07772f7a3e7501976cf17515c4c7993:400dc81c5cc6ca060d11b3c65ad87fa9e07772f7a3e7501976cf17515c4c7993

Embed code probably will be something like this

```html
<iframe
  style="border-radius:12px"
  src="https://open.spotify.com/embed/track/0Kze26iCzT0tap9FtpQqHa?utm_source=generator"
  width="100%"
  height="352"
  frameBorder="0"
  allowfullscreen=""
  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
  loading="lazy"
></iframe>
```

**Comment by verbiricha** [comment]
pls send patches, we are overwhelmed 😹

**Comment by SamSamskies** [comment]
Roger dat
