### ISSUE TITLE
Snort is posting new notes as replies to random notes 

### ISSUE THREAD

**Issue by dskvr** [v0l/snort#189]
**Describe the bug**
Clicked "+" and authored a new note, like I have many times before. The note was published as a reply to random notes, some of which I had never interacted with. This started sometime in the last couple hours. 

I did attempt to refresh and cleared local data. 

**To Reproduce**
Not sure if it is replicable, but...
1. Click "+"
2. Post a new note
3. Observe 

**Expected behavior**
A new note is a new note without a parent, not a reply to a note. 

**Screenshots**
![Screen Shot 2023-02-02 at 2 00 48 AM](https://user-images.githubusercontent.com/299465/216205151-e470a6bc-6794-4ab9-a7ff-9c7e06b58640.png)

**Desktop (please complete the following information):**
Contact me if you need this info. 

**Smartphone (please complete the following information):**
n/a

**Comment by SamSamskies** [comment]
+1. This was happening to me as well today when I was testing a new account in development. Here's [an example note ](https://snort.social/e/note1rk50pff7r6rhtp4xghdt4ecve82lquma3zhxfkaz564cdzrqstcsfdzgcz)where I clicked the plus button to add a new note and it added it as a reply to one of Jack's notes that I don't even remember interacting with.

**Comment by dskvr** [comment]
Thank you @v0l !!!!
