### ISSUE TITLE
Restore scroll position

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#19]
Hi,

When I click on a message that opens a thread and then I go back by using Android back button, should send me to the position I was in the feed.

The way works now goes to the top. 

Thanks.

**Comment by v0l** [comment]
Not sure how doable this is, we load the content async so its not currently possible to scroll back down because the page content is empty initially

**Comment by v0l** [comment]
Partially fixed with switch to `react-router` data routes

**Comment by bitcoinuser** [comment]
For now on mobile if I go to "Posts and replies" tab and click to open a thread and then I click on Android Back button, it send me to "Posts" tab and not "Posts and replies" tab as should be.
