### ISSUE TITLE
Tidal music Link just shows album cover

### ISSUE THREAD

**Issue by BdGBertdeGroot** [v0l/snort#192]
**Is your feature request related to a problem? Please describe.**
You just see the cover as if it is a picture. When you click the picture you see the actual playlist within the frame. The posted link to tidal should show something where you can actually recognise it's a music link.

**Describe the solution you'd like**
Something that shows that this is a link to tidal? 

**Describe alternatives you've considered**
?

**Additional context**
None
<img width="735" alt="Screenshot 2023-02-02
<img width="734" alt="Screenshot 2023-02-02 at 23 52 43" src="https://user-images.githubusercontent.com/88569777/216469806-ab638238-5557-4a11-9c16-054feac78ab3.png">
 at 23 55 24" src="https://user-images.githubusercontent.com/88569777/216469794-bf54d4b6-3dde-4e90-9be6-120a677a5b28.png">

**Comment by enjikaka** [comment]
This is fixed here with my PR: https://github.com/v0l/snort/pull/191

The old embed player in the image above shows a cover image above the player, slides to show to player on click. The new one doesn't have that.
