### ISSUE TITLE
keyboard shnorts

### ISSUE THREAD

**Issue by sjorsvanheuveln** [v0l/snort#195]
**Is your feature request related to a problem? Please describe.**
cmd + enter for replying for the keyboard ninjas would be great.
Also cmd + n (or m) for a new note also recommended

**Describe the solution you'd like**
Twitter has this and it's really great and easy to implement. Will make UX a lot better.

**Comment by mdebus** [comment]
+1

I'd like VIM like keyboard shortcuts. j+k for moving up and down posts etc. like in Pinafore for Mastodon would be great.
