### ISSUE TITLE
Profile tip button is showing even if user hasn't set up a Lightning Address

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#197]
Probably shouldn't show the lightning tip button on a user's profile if they don't have a Lightning Address set on their profile.

https://snort.social/p/npub1nw5vdz8sj89y3h3tp7dunx8rhsm2qzfpf8ujq9m8mfvjsjth0uwqs9n2gn

Yellow's profile on 

Snort 

![Screenshot 2023-02-04 at 7 07 11 PM](https://user-images.githubusercontent.com/3655410/216796410-6138487b-ac40-461b-ae88-efe07f414617.png)

vs

Damus

![IMG_10D22798DF81-1](https://user-images.githubusercontent.com/3655410/216796483-7b438f7f-6da4-4e3e-828e-04ef78a41bfe.jpeg)

**Comment by verbiricha** [comment]
good catch, fixed in https://github.com/v0l/snort/pull/199
