### ISSUE TITLE
⚡ Lightning integration

### ISSUE THREAD

**Issue by reneaaron** [v0l/snort#20]
First of all: congrats to this great client, I now use it on mobile as well as on desktop all the time. 🤙

I noticed different problems with the current integration of lightning payments: 

### CORS

Resolving lightning addresses currently doesn't work for a lot of lightning addresses (e.g. WoS). Resolvign them on client-side requires the lightning address host to add certain headers in order for those requests to work. 

![image](https://user-images.githubusercontent.com/100827540/211202042-e4d7b286-3ee2-4660-80a0-d89ba573c67b.png)

![image](https://user-images.githubusercontent.com/100827540/211202111-341a8399-89b0-469d-97f6-2efdeb1d5102.png)

Potentially you could host an invoice endpoint and request invoices there (kind of a [proxy](https://github.com/reneaaron/lightning-widget/blob/master/src/server/main.js#L20) for the provided LNURL) to avoid any CORS issues.

### Wallet UI

Telling from several real-world experiences I'd say a lot of users don't know that they can click QR-Codes. 

![image](https://user-images.githubusercontent.com/100827540/211202266-804498f4-09e8-427c-83bb-51730f802072.png)

I could imagine something like this here: 

![image](https://user-images.githubusercontent.com/100827540/211202349-915694cf-1a1a-4667-ba16-7979daa48c9f.png)

The QR code could still be a link, but I think it would be great to have some more explicit options for users. (buttons to copy / open in wallet)

### WebLN

You could conditionally check for `window.webln` and trigger the payment with `webln.sendPayment()`. That would allow users with browser extensions to set a budget for your site and do payments with just one click (instead of having to scan QR codes or copying invoices).

https://github.com/v0l/snort/commit/037f39e3864b40c8ba9744dbf16d33c4a17c8bc4#diff-9d45cafb0e2ed16048c135c9fd71f06c8f4cd08aabd660e8d558439d89eabe74R32

```
if(window.webln) {
  await window.webln.enable();
  await window.webln.sendPayment(link);
}
```

**Comment by v0l** [comment]
Hey thanks for the feedback, all valid points the send sats UI needs improvements

**Comment by v0l** [comment]
I added WebLN and some more buttons, the CORS issues ill have to fix some other way, ideally the common wallets would just add CORS headers though...
