### ISSUE TITLE
Show reply count next to reply icon

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#210]

**Comment by Maniyuvan** [comment]
Can you provide some description to understand the issue better?

**Comment by verbiricha** [comment]
The idea is to show the total number of replies a note has next to the reply icon.

I think what we can do is fetch replies to a note as part of the reactions suscription and count the replies to show them in the note footer.

**Comment by verbiricha** [comment]
actually I only think makes sense to show this for notes that are rendered in a thread (perhaps even only root note) since at that point we have fetched the thread and can know how many replies each note has.

**Comment by joshr4** [comment]
I'm attempting to implement this, I have a draft PR here https://github.com/v0l/snort/pull/299

**Comment by tincho70** [comment]
Is there any chance of implement this feature?
