### ISSUE TITLE
Autoscroll to last message received in DM view

### ISSUE THREAD

**Issue by 0xtrr** [v0l/snort#213]
**Is your feature request related to a problem? Please describe.**
When I open a DM view, the very first message between me and the other user is displayed. I think autoscrolling to the bottom/last message sent/received would make more sense.

**Describe the solution you'd like**
When I open a DM, it should show me the last message received, i.e. auto scroll to the bottom of the DMs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by verbiricha** [comment]
Solved by #250 , thanks for reporting!
