### ISSUE TITLE
Buttons on ProfilePage don't fit horizontally with Spanish translations

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#226]
The last button is cut off on the right side.

![Screenshot 2023-02-08 at 5 16 58 PM](https://user-images.githubusercontent.com/3655410/217673679-50bec14b-6f6c-46be-b52f-366e283f4a1c.png)

**Comment by v0l** [comment]
That should scroll anyway?

**Comment by SamSamskies** [comment]
Yeah it scrolls. Just looks a little janky.

**Comment by SamSamskies** [comment]
YouTube collapses the last button in a row into a `...` button when the screen width shrinks. Maybe we could copy that.

![Screenshot 2023-02-08 at 7 39 47 PM](https://user-images.githubusercontent.com/3655410/217693285-f25f1d66-7d2b-4ca9-8610-f8eb99d04e51.png)

![Screenshot 2023-02-08 at 7 40 02 PM](https://user-images.githubusercontent.com/3655410/217693297-adaeeb90-3021-47b3-af12-b31cab180ff7.png)

**Comment by v0l** [comment]
Some tabs are optional now, so this should not be a problem
