### ISSUE TITLE
Add Snort to Umbrel App Store

### ISSUE THREAD

**Issue by nevets963** [v0l/snort#232]
**Is your feature request related to a problem? Please describe.**
It would be awesome to easily install Snort on an Umbrel server through their App Store. Making Nostr clients easily accessible like this is another avenue to gain traction. Additionally as apps on Umbrel are served over HTTP, it will allow the client to connect to relays using `ws://` such as Umbrel's private Nostr Relay: https://twitter.com/umbrel/status/1622591145481236480 

**Describe the solution you'd like**
Firstly, we'll create a `Dockerfile` to build Snort and then a GH workflow to automatically build and push a Docker image to the Docker Hub. Would you accept a PR that adds a `Dockerfile` and GitHub workflow to automatically build and push a Docker image to the Docker Hub? I've done these before where it's triggered when a new tag is created that marks a new version (e.g. `v1.2.3`), so this would also mean that new tags would need to be created as new versions of Snort go live.

**Describe alternatives you've considered**
An alternative approach could be if someone manually builds and pushes Docker images.

**Additional context**
Some extra detail about the Umbrel App Store: https://umbrel.com/#app-store
However, once Docker images are created, I can also help with the app submission into the App Store.

**Comment by v0l** [comment]
Hey, thanks for the issue, i already started to build Docker images, im quite familiar with the process so im happy to do this myself.

Available time is an issue for me though, so im not sure when it will be done (though i imagine that i could be completed before next week)

One problem i see here is that we currently don't have versioning in place, Is this a problem for Umbrel app store?

**Comment by nevets963** [comment]
Nice! All apps in the App Store must a version because 1) it allows users to report issues quoting a specific version and 2) the update system relies on this field to know if an app update is available. I guess if you wanted to avoid e.g. semver then you could use the first few characters of the commit ID.

**Comment by v0l** [comment]
How frequent can we update the Umbrel app store, we're pushing many changes every single day which get automatically deployed live, wouldn't be a great experience if people are expecting features or wanting features on their local instance

**Comment by nevets963** [comment]
As frequently as you want 😄 I'm currently managing the app submissions and updates (hosted here: https://github.com/getumbrel/umbrel-apps). The `docker-compose.yml` file and app manifest (`umbrel-app.yml`) for the app would need updated each time, but perhaps it makes sense to do this once every 1 to 2 weeks?

**Comment by v0l** [comment]
Pushed simple latest build here: https://github.com/v0l/snort/pkgs/container/snort

will setup weekly versioned build tomorrow

**Comment by nevets963** [comment]
Awesome, once there is a tagged Docker image available, I can help with the app submission 😄 

Is this is a multi-arch image? It shows me `unknown/unknown` for the 2nd available arch; because we'll need both `arm64` and `amd64` support.

**Comment by v0l** [comment]
Yea i had `arm64` builds but it kept timing out, do you recommend using `buildx` or something else?

**Comment by nevets963** [comment]
Yh, we use `buildx` for everything. Here is an example of a GitHub workflow that we use to automate everything: https://github.com/getumbrel/umbrel-manager/blob/fc823490591ea55e26734d144a0527fe9618166d/.github/workflows/on-tag.yml

**Comment by v0l** [comment]
Haha 1hr 6min to build... wtf

**Comment by v0l** [comment]
Ok i have created a tagged version now, what is the next step? https://github.com/v0l/snort/pkgs/container/snort/69991596?tag=v0.1.0

**Comment by v0l** [comment]
PR is open, closing this

**Comment by JimSB** [comment]
hi i just wanted to double check here if ws:// support is added yet?
