### ISSUE TITLE
Long nip5 causes reactions modal to look janky

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#236]
Follow/unfollow button height expands when a user has a long nip5 and the button overlaps the nip5 text. Would it be better to just remove the follow/unfollow button? Users can easily just click on the row to go to the user's profile page and follow/unfollow there.

![Screenshot 2023-02-09 at 1 00 28 PM](https://user-images.githubusercontent.com/3655410/217912060-36f50c7e-c61d-4cdd-aa40-3c9611816c78.png)

**Comment by verbiricha** [comment]
+1, also looks terrible in spanish

**Comment by v0l** [comment]
"Kill that follow button"

**Comment by SamSamskies** [comment]
I can do it. I love deleting code. 😂
