### ISSUE TITLE
Search not working?

### ISSUE THREAD

**Issue by xttlegendapi** [v0l/snort#276]
**Describe the bug**
Search not working

**To Reproduce**

1. Click on search
2. Search something
3. Doesnt work, keeps loading

**Expected behavior**
Give search results, as with the old search

**Screenshots**

https://user-images.githubusercontent.com/103502418/218311051-0ed946fe-9dfc-4bdc-a4d5-1d99a59b1a63.mov

The old search DOES work! ^

**Desktop (please complete the following information):**

- OS: Fedora Linux (latest)
- Browser: Chromium, Firefox
- Version: Latest

**Smartphone (please complete the following information):**

- Device: Google Pixel 6a
- OS: CalyxOS Latest
- Browser: Chromium
- Version Latest

**Additional context**

**Comment by v0l** [comment]
This is backed by @brugeman's search relay maybe its down?

**Comment by brugeman** [comment]
My relay is in trouble, fixing it as soon as I can, sorry about this.
