### ISSUE TITLE
nostr.json

### ISSUE THREAD

**Issue by bokybanton** [v0l/snort#302]
I want to tell the nostr.json with all nip-05 names vinculated with pubkeys are all public online and I think it would be bad if somebody gets it to spam snort users...

**Comment by bokybanton** [comment]
I think It must output only when ?name=xxxx is prompted on uri ...  I mean on snort.social/.well-known/nostr.json could you restrict it ?

**Comment by v0l** [comment]
Thanks for the feedback, pushed a fix for this
