### ISSUE TITLE
The SAVE button on the profile page does not work

### ISSUE THREAD

**Issue by mcf-rocks** [v0l/snort#310]
**Describe the bug**
I added a profile image, a background image, an LN address and pressed SAVE

**To Reproduce**

Try it for yourself

**Expected behavior**
I expected it to save.

**Desktop (please complete the following information):**

Chrome on MacOS

**Comment by joshr4** [comment]
possibly related to https://github.com/v0l/snort/issues/173

**Comment by v0l** [comment]
No feedback on the button that's all, it does work
