### ISSUE TITLE
Relays listed on profile sometimes don't match relays listed in settings

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#317]
**Describe the bug**
Earlier today I added wss://nostr-dev.wellorder.net/, but I later deleted it because it wasn't working. For some reason my profile on Snort is still displaying it. The relay page in the settings is correct though.

**To Reproduce**
Not sure how to reproduce. Try adding and then removing a relay.

**Expected behavior**
When I click the Relays pill on my profile, the listed relays match what's in my my settings.

**Screenshots**
Relays on settings page is correct
![Screenshot 2023-02-15 at 7 06 15 PM](https://user-images.githubusercontent.com/3655410/219232129-4e0aeca3-c482-4616-8fc8-27c2b5cd28d9.png)

Relays on profile is not correct
![Screenshot 2023-02-15 at 7 05 46 PM](https://user-images.githubusercontent.com/3655410/219232094-4911cd8c-aec8-4df6-885b-bfceb253318c.png)

**Comment by verbiricha** [comment]
I think this is because we are caching the relay list result, we shouldn't so we always show the latest https://github.com/v0l/snort/blob/main/packages/app/src/Feed/RelaysFeed.tsx#L16

**Comment by SamSamskies** [comment]
I did more research on this and when I query relays for kind 10002 for my account I get an outdated list of relays. @v0l @verbiricha are we forgetting to broadcast a kind 10002 event when updating the relays on Snort? Is that how [nip-65](https://github.com/nostr-protocol/nips/blob/524caa38563f49fc2aacbbe48b212fde0f24f97e/65.md) is supposed to work? If that's what we're supposed to do, we could use [Blastr (wss://nostr.mutinywallet.com)](https://github.com/MutinyWallet/blastr) to broadcast the 10002 update when a user updates their relays on Snort.

**Comment by SamSamskies** [comment]
I think I see the bug in our code, I'll make a PR and we can discuss there if I'm misunderstanding how this is supposed to work.

**Comment by verbiricha** [comment]
> are we forgetting to broadcast a kind 10002 event when updating the relays on Snort? Is that how [nip-65](https://github.com/nostr-protocol/nips/blob/524caa38563f49fc2aacbbe48b212fde0f24f97e/65.md) is supposed to work?

When saving relays settings we should be broadcasting to all the relays we are connected to and a few others but perhaps there is a bug there.

> we could use [Blastr (wss://nostr.mutinywallet.com)](https://github.com/MutinyWallet/blastr) to broadcast the 10002 update when a user updates their relays on Snort.

This would be perfect since we want updated 10002 events to be on every relay possible.
