### ISSUE TITLE
Search returns global feed if query is non-ascii

### ISSUE THREAD

**Issue by nostrband** [v0l/snort#325]
**Describe the bug**
When I search for тест I expect to see matching results.

**To Reproduce**
1. Go to https://snort.social/search/
2. Type тест or テスト
3. See irrelevant results

**Expected behavior**
Results should match the query.

**Additional context**
Irrelevant stuff is coming from wss://knostr.neutrine.com

**Comment by v0l** [comment]
4a7d90c
