### ISSUE TITLE
Feature Request: Select which relays you want to see in the global feed

### ISSUE THREAD

**Issue by 0xtrr** [v0l/snort#328]
In the currently deployed version of Snort, I'm only able to read the global feed from a few specific relays. I'd like to be able to choose which ones are used to populate the global feed and not be restricted to a specific set that someone else have selected for me.

**Comment by v0l** [comment]
Global feed selector only shows your relays which are paid relays, i could change it to a hard coded list of paid relays?

**Comment by 0xtrr** [comment]
Honestly, I'd just want to be able to select/deselect which relays I want to use for the global feed. E.g. my own relay wss://nostr.oxtr.dev isn't paid but I might want to only populate the global feed with that relay + one or more of my paid relays.

What about defaulting to the user's paid relays as you do today but also let the user select/deselect which relays they want to use in the global feed?

**Comment by v0l** [comment]
Implemented
