### ISSUE TITLE
Zap Fails to load LNURL

### ISSUE THREAD

**Issue by orangesurf** [v0l/snort#332]
**Describe the bug**
Snort fails to load LNURL service when making a zap to sats@tips.orange.surf, but payments work from other nostr interfaces (damua) and to the LN Address from coinos & stacker news. Even when the error appears in snort an invoice is created in my btcpayserver 

Invoice Created in BTCPayServer 
![image](https://user-images.githubusercontent.com/91332210/219943114-091c7c19-515e-4784-adf2-0ace41ee01a0.png)

Failure Message
![failed-to-load-lnurl](https://user-images.githubusercontent.com/91332210/219943087-06012b6c-334a-4d89-a57a-a8ccd23bc0c2.png)

**To Reproduce**

1. Go to https://snort.social/p/npub18h0w55nsp839ezxnggf00jd2xc6yl0ht62mf5p8wwllu8s80wdcs83ws8m
2. Click on sats@tips.orange.surf
3. Wait 1 second
4. See error (Failed to load LNURL service)

**Expected behavior**
Expected Zap payments widget to open

**Comment by v0l** [comment]
Update your BTCPayServer (added CORS headers)
