### ISSUE TITLE
NIP-57 zap request is not signed

### ISSUE THREAD

**Issue by mutatrum** [v0l/snort#338]
The NIP-57 zap request that's sent to the Lightning Address handler doesn't have an id and is not signed.

**Comment by mutatrum** [comment]
It seems to be fixed after logging in again. Can it be snort loses login credentials somewhere, and still produces a zap request if there's no login information?

**Comment by v0l** [comment]
If you're using NIP7 extensions sometimes it doesnt work, Alby requires password usually
