### ISSUE TITLE
Don't show replies to yourself in Notifications

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#34]
When reacting to one of your notes with a reply it shows up in Notifications, is this what we want?

**Comment by v0l** [comment]
Really? It shouldnt, we only count notifications from text notes

**Comment by verbiricha** [comment]
I mean when replying to yourself with a note event, not a reaction event. <img width="755" alt="Screenshot 2023-01-12 at 13 51 32" src="https://user-images.githubusercontent.com/92299987/212071112-9ca97138-da7e-4bfe-a379-0241fb5ccb4b.png">

**Comment by v0l** [comment]
That should be fixed recently, it will remove your own pubkey if you're replying in a thread, if you reply directly to your own note its still there afaik, maybe thats the case here?

**Comment by v0l** [comment]
Resolved, we never add our own pubkey in replies now
