### ISSUE TITLE
Add ability to link to notes using nevent id format

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#369]
**Is your feature request related to a problem? Please describe.**

https://snort.social/e/note1mwv87l4q4x8hapqmp6vwhua2lzlwvw6eeqssvykzmq907j4tdnhswf8wkv

![Screenshot 2023-02-27 at 10 00 55 AM](https://user-images.githubusercontent.com/3655410/221615269-a70f7fc7-e51f-431e-b2d7-9b686f0e46db.png)

**Describe the solution you'd like**
Add support for `nevent` links. For example, going to a link with an `nevent` ID should connect to relays decoded from the ID if necessary and then render the note.

Example link could look like this:
https://snort.social/e/nevent1qqsy26z4sg7vy4afp2g0ptmc8f930tns05jy6ckd3cw095shrhhmmvcpz4mhxue69uhhyetvv9ujumt0wd68ytnsw43qe2wps6

Maybe also updating the share links to use these `nevent` links instead of the `note` links.

**Comment by v0l** [comment]
Done
