### ISSUE TITLE
LND LNC error: Not a proper lightning payment request

### ISSUE THREAD

**Issue by aphex3k** [v0l/snort#383]
**Describe the bug**
I used LND LNC to connect to my node running lnd v0.15 and I get an error after correctly pairing and entering the wallet password.

**Screenshots**

![image](https://user-images.githubusercontent.com/433270/222541375-d8851661-acc9-44fb-8161-00736c53d354.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Brave
- Version: .48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)

**Additional context**
I generated the pairing phrase in lightning terminal and it seems to pair correctly to the node as it shows my node alias correctly.

**Comment by v0l** [comment]
I added more logging can you check again?

**Comment by aphex3k** [comment]
> I added more logging can you check again?

I'm using `ghcr.io/v0l/snort:latest` but it hasn't updated yet...

**Comment by v0l** [comment]
> > I added more logging can you check again?
> 
> I'm using `ghcr.io/v0l/snort:latest` but it hasn't updated yet...

Yea builds take about 30mins for docker (thanks to ARM64)

**Comment by aphex3k** [comment]
Pasting the log as (redacted) file. It looks like it fetches the last 10 payments but fails to parse the information it receives back?

[wallet-1677797240316.log](https://github.com/v0l/snort/files/10876473/wallet-1677797240316.log)

**Comment by aphex3k** [comment]
The UI flashes after entering the password to a wallet screen for a brief second before showing an error screen.

> Pasting the log as (redacted) file. It looks like it fetches the last 10 payments but fails to parse the information it receives back?
> 
> [wallet-1677797240316.log](https://github.com/v0l/snort/files/10876473/wallet-1677797240316.log)

sorry, the above is the old log...

This one is the log from the updated version: 
[wallet-1677797936857.log](https://github.com/v0l/snort/files/10876518/wallet-1677797936857.log)

![image](https://user-images.githubusercontent.com/433270/222579635-4444d216-2667-4e3e-adb5-dd8640d67fb9.png)

**Comment by aphex3k** [comment]
![image](https://user-images.githubusercontent.com/433270/222586876-4d1d0d73-8446-4a3a-a924-05b33ca6dd97.png)
![image](https://user-images.githubusercontent.com/433270/222586948-4a9df9f1-4742-472d-a818-25757739f59b.png)
When I attempt zapping a post I receive the following error. Not sure if this really provides any additional information.

**Comment by v0l** [comment]
I dont see the logs that i added did you remove them?

**Comment by v0l** [comment]
Regarding the zapping issue, did you first unlock the wallet? You need to go to the wallet page and enter password

**Comment by aphex3k** [comment]
[wallet-1677860772690.log](https://github.com/v0l/snort/files/10884139/wallet-1677860772690.log)

Here is a log file that was started before entering the wallet password until after the error is displayed.

I did not remove any lines from the log files, I do however replace mentions of hosts and keys with `<redacted>`.

**Comment by aphex3k** [comment]
> Regarding the zapping issue, did you first unlock the wallet? You need to go to the wallet page and enter password

Thanks for the remark. Unlocking the wallet first and zapping second works as expected!

**Comment by v0l** [comment]
Ok so you can make payments but not view history, did you generate a session with read & activity permission?

**Comment by aphex3k** [comment]
> Ok so you can make payments but not view history, did you generate a session with read & activity permission?

I can double-check. I used the default settings but they might not be inclusive on the permissions...

**Comment by aphex3k** [comment]
> > Ok so you can make payments but not view history, did you generate a session with read & activity permission?
> 
> I can double-check. I used the default settings but they might not be inclusive on the permissions...

I created and connected to a new session that specifically mentions ADMIN permissions and I'm still seeing the same error.
