### ISSUE TITLE
New DM design

### ISSUE THREAD

**Issue by v0l** [v0l/snort#388]
Implement new DM design from [Figma](https://www.figma.com/file/Q79i1WVA1bIAzYaLihgteN/Snort?node-id=0%3A1)

**Comment by villenmarx** [comment]
Hi v0l.

Snort ui/ux design looks a lot like [OpenXanadu](https://xanadu.com/xanademos/MoeJusteOrigins.html) design. For example,

OpenXanadu |  snort
:------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/126974943/222965204-ec3953af-26fd-43bc-83b6-edbb56855918.png" width="950px" alt="image"/>  |  <img src="https://user-images.githubusercontent.com/126974943/222965250-f62be490-0fb3-468f-8a5a-6ee6d674b94f.png" width="550px" alt="image"/>

Were you all inspired by the idea of ​​ted nelson?
