### ISSUE TITLE
Reply dialog sometimes closes when you're in the middle of typing a reply

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#408]
**When does this happen?**
This seems to happen when there's a lot of people replying to a note and the timeline re-renders. 

**Expected behavior**
Reply dialog doesn't disappear while you are in the middle or replying.

**Possible solutions**
- The dialog could be rendered in a portal outside of the timeline so that if the timeline re-renders, the dialog doesn't also re-render
- Save draft states of replies in redux so that you can continue with a draft state when you re-open the dialog

**Comment by Giszmo** [comment]
Bump to prevent this from getting closed. This still is happening and it's slightly infuriating ;)

**Comment by SamSamskies** [comment]
I can take a crack at this. It's been annoying me as well. 😂
