### ISSUE TITLE
Skeleton loaders should go away after a timeout

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#420]
**Is your feature request related to a problem? Please describe.**
For a new user, they permanently see skeleton loading states on their profile page even though nothing is loading.

![Screenshot 2023-03-09 at 2 38 14 PM](https://user-images.githubusercontent.com/3655410/224151731-c59fa722-954c-4a5c-89a4-633383afe1b7.png)

**Describe the solution you'd like**
Hide skeleton loaders after a short timeout.

**Comment by v0l** [comment]
LoadMore is removed from Profile page
