### ISSUE TITLE
Logout and login again on Snort using Alby, make Snort loose the preferences I set

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#428]
Hi,

Logout and login again on Snort using Alby, make Snort loose the preferences I set.

Thanks.

**Comment by bitcoinuser** [comment]
Maybe implement this NIP: https://github.com/nostr-protocol/nips/blob/master/78.md

**Comment by v0l** [comment]
Duplicate https://github.com/v0l/snort/issues/379
