### ISSUE TITLE
I'm being requested to send 3 sats many times always when I zap someone

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#431]
Hi, 

I don't have auto zaps enabled but I have Default zap amount enabled to 10 sats and Fast Zap Donation 30.

Always when I zap someone I'm requested to pay 10 sats, that is ok, and then 3 sats that is ok too, but after I pay the 3 sats, the Alby popup indefinitely to pay 3 sats again and again and again.

**Comment by v0l** [comment]
Oh maybe i introduced a bug in the FastZap donations? Do you have that turned on?

**Comment by bitcoinuser** [comment]
> Oh maybe i introduced a bug in the FastZap donations? Do you have that turned on?

Yes, fast donation on 30% that is 3 sats because default zap donation is 10 sats.

**Comment by bitcoinuser** [comment]
> Oh maybe i introduced a bug in the FastZap donations? Do you have that turned on?

Yes, I think you introduced a bug, because it was working correctly when you released it.

**Comment by v0l** [comment]
Yea there was a loop, pushed a fix

**Comment by bitcoinuser** [comment]
> Yea there was a loop, pushed a fix

Confirmed is working ok now. Thanks.

**Comment by bitcoinuser** [comment]
Hum, Looks like I reproduced this again.

**Comment by bitcoinuser** [comment]
> Hum, Looks like I reproduced this again.

Back to normal, if I reproduce again, I tell you here.
