### ISSUE TITLE
Looks like share button does not share. Share is like retweet, right?

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#433]
Hi

Looks like share button does not share. Share is like retweet, right?

Please verify if is not broken. Thanks.

**Comment by SamSamskies** [comment]
Share copies the link to the event to your clipboard.

**Comment by bitcoinuser** [comment]
Hum, ok

**Comment by bitcoinuser** [comment]
> Share copies the link to the event to your clipboard.

Why I don't see repost button?

![Captura de tela de 2023-03-13 17-15-47](https://user-images.githubusercontent.com/1178856/224822289-48b1358c-fafa-4d4c-8da9-9dd3c20e0026.png)

**Comment by SamSamskies** [comment]
you need to enable it in the settings

![Screenshot 2023-03-13 at 3 30 37 PM](https://user-images.githubusercontent.com/3655410/224825358-1009dc1f-ff94-4b31-8af1-467fddff8661.png)

**Comment by bitcoinuser** [comment]
> you need to enable it in the settings
> 
> ![Screenshot 2023-03-13 at 3 30 37 PM](https://user-images.githubusercontent.com/3655410/224825358-1009dc1f-ff94-4b31-8af1-467fddff8661.png)

Thanks
