### ISSUE TITLE
Authoring a reply while another note comes in, causes loss of data

### ISSUE THREAD

**Issue by Giszmo** [v0l/snort#438]
**Describe the bug**

I was polishing my reply when all of a sudden stuff moved under the modal and the modal with my carefully crafted note closed. Upon re-opening it, it was empty.

**Expected behavior**

New notes should be added without data loss.
Closing and opening the editor should restore the unsent note.

**Desktop (please complete the following information):**

- OS: debian
- Browser: FF
- Version: 96.0.3 (64-bit)

**Comment by SamSamskies** [comment]
I think this is a duplicate https://github.com/v0l/snort/issues/408

**Comment by Giszmo** [comment]
Yep. I think you are right.
