### ISSUE TITLE
Add an option to share the zaps on reposts

### ISSUE THREAD

**Issue by bitcoinuser** [v0l/snort#443]
Hi,

I was thinking if is possible to: 

1- I create a post
2- When creating my post I specify that if person X repost my post and person Y zap the post using person X repost, the person X receive a share % of the zap that Y person sent.

Thanks.

**Comment by v0l** [comment]
I had a similar idea for zapping when somebody follows you, but i dont think this is something that can be done in clients, seems more like a bot feature?

**Comment by v0l** [comment]
Also there wont be a way to tell if somebody zapped from a repost unless we add some extra tags to the zap
