### ISSUE TITLE
Beginners can't find people with the default relay setting

### ISSUE THREAD

**Issue by koteitan** [v0l/snort#447]
Now we have random 4 relays as default relays.

That is too few to find particular persons for new guys that start nostr from snort.

For example, when two new guys sign up nostr by snort, they can't see them each other unless there is a common relay in their 4 relays.

Snort should includes more relays and famous relays in default relays.

**Comment by koteitan** [comment]
For example, default relays were set when I create two accounts as follows:

- account 1
  - wss://nostr01.opencult.com
  - wss://nostr.easify.de
  - wss://btcpay.kukks.org/nostr...(unread completely)
  - wss://nostr.tools.global.id

- account 2
  - wss://arnostr.permadao.io
  - wss://nostream.nostrly.io
  - wss://jp-relay-nostr.invr.chat
  - sww://nostr.itrednek.com
 
They can't find people they wants, even themselves, even if they are friend.

**Comment by koteitan** [comment]
However, there are some opinions which say that leading to the most commonly used relays occurs centralization and overload.
https://mikedilger.com/gossip-model/
I'd like to know your opinion.

**Comment by Giszmo** [comment]
Please read some events from 100 "good" relays! I tried to onboard somebody and create a secondary account for myself and it's a total disaster! Changes seemingly don't get persisted at all. Accounts are not found, etc.

Please, once the pubkey is known, load it from as many relays as possible. Load follows and their profiles from these relays, too. Write the profile to those relays, too so others can discover them.

**Comment by v0l** [comment]
I added the default relays for new users now, they get 4 random relays + the default relays
