### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by Giszmo** [v0l/snort#457]
**Describe the bug**
Searching for _@WalletScrutiny.com yields the respective nip05 account twice.

![Screenshot from 2023-03-23 15-08-22](https://user-images.githubusercontent.com/96378/227306452-00bbc9e2-e1de-4339-8322-f7453fc4767f.png)

**Comment by ivanacostarubio** [comment]
It should be ok when we merge https://github.com/v0l/snort/pull/378
