### ISSUE TITLE
Parent notes are not rendering when loading a reply note page

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#468]
**Describe the bug**
The parent of reply notes are not rendering anymore when loading a reply note, so now it's not possible to traverse up threads. I think this broke when switching from note ids to event ids.

https://snort.social/e/nevent1qqsvn0g5czk3vhyyz0ud3ck3fpllpcuyjlr4sdcaxxcdskr7wggz9wqpz3mhxue69uhhyetvv9ujuerpd46hxtnfdu26y9fj

<img width="642" alt="Screenshot 2023-03-28 at 9 35 16 PM" src="https://user-images.githubusercontent.com/3655410/228420330-4390df4e-ab8a-4c19-8425-df0f70d2d568.png">

**To Reproduce**
Load a note that is a reply to another note e.g. https://snort.social/e/nevent1qqsvn0g5czk3vhyyz0ud3ck3fpllpcuyjlr4sdcaxxcdskr7wggz9wqpz3mhxue69uhhyetvv9ujuerpd46hxt

**Expected behavior**
There should be a way to traverse up a thread to view the conversation or there should be a way to view the entire thread.

**Comment by v0l** [comment]
Fixed in #326
