### ISSUE TITLE
Copy ID on popup menu of note always copy nevent1xxx instead of note1xxx.

### ISSUE THREAD

**Issue by mattn** [v0l/snort#471]
**Describe the bug**

Copy ID on popup menu of note always copy nevent1xxx instead of note1xxx.

**To Reproduce**

Click button `︙` and click "Copy ID"

**Screenshots**

![image](https://user-images.githubusercontent.com/10111/228867851-95317ef1-0df7-4672-99bb-825e54224ee5.png)

- OS: Linux/Android/Windows...
- Browser Google Chrome
- Version latest

**Comment by mattn** [comment]
Yes, but nevent can't be used for quoted post like below.

```
I know it

@note1xxx
```

**Comment by v0l** [comment]
I see, so this is an issue with quoting events

**Comment by v0l** [comment]
Fixed recently
