### ISSUE TITLE
Appimage fails to run under Wayland

### ISSUE THREAD

**Issue by mariaa144** [v0l/snort#475]
**Describe the bug**
The AppImage will not launch under a Wayland desktop on Linux.

**To Reproduce**

1. Run Wayland
2. Launch AppImage
3. Notice errors and crash

**Expected behavior**
Snort would launch normally under Wayland

**Logs**
```
RUST_BACKTRACE=1 ./snort_0.1.5_amd64.AppImage
thread 'main' panicked at 'data.len() must fit the width, height, and row_stride', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdk-pixbuf-0.15.11/src/pixbuf.rs:52:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: tao::platform_impl::platform::icon::<impl core::convert::From<tao::platform_impl::platform::icon::PlatformIcon> for gdk_pixbuf::auto::pixbuf::Pixbuf>::from
   3: tao::platform_impl::platform::window::Window::new
   4: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::create_window
   5: tauri::app::Builder<R>::run
   6: app::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**My OS**
- OS: Arch Linux using Wayland on Gnome

**Additional context**
This seems to be an upstream issue with Tarui. https://github.com/tauri-apps/tauri-egui/issues/7

**Comment by bitnorbert** [comment]
This doesn't seem to be Wayland specific. I get the same error on X11 with KDE on Debian 11. It's also not specific to AppImage, as I get the error there as well as with `/usr/bin/snort` from deb package.
