### ISSUE TITLE
Datas not loading or Loading Slow 

### ISSUE THREAD

**Issue by yhoungdev** [v0l/snort#477]
**Describe the bug**
This issue describes an issue i have been facing for some months now, it's not loading up data, and sometimes loading it up slowly. 

**To Reproduce**

* Check on any profile 

**Expected behavior**
Data should be loaded immediately i try fetching the data 

**Screenshots**
![Screenshot from 2023-04-01 04-31-27](https://user-images.githubusercontent.com/54102389/229264445-afbe063f-7eda-4084-8426-83b1ddefbaeb.png)

**Comment by v0l** [comment]
Data may not be loaded because the user has no posts and we are "scanning" time ranges to find something, The look of this loading pattern bothers many people but im not sure how to better represent that we're looking for content...

**Comment by vivganes** [comment]
> Data may not be loaded because the user has no posts and we are "scanning" time ranges to find something, The look of this loading pattern bothers many people but im not sure how to better represent that we're looking for content...

Submitted a PR (https://github.com/v0l/snort/pull/492) with a proposal. Not sure if you like the approach. @v0l

**Comment by v0l** [comment]
Resolved now, profile page loads latest 200 notes ONLY
