### ISSUE TITLE
UnknownEventKind 6

### ISSUE THREAD

**Issue by mattn** [v0l/snort#479]
**Describe the bug**

kind:6 but UnknownEventKind occured.

**To Reproduce**

See https://snort.social/e/note19lcv9jck7gu9kj2e5wwyz5kr8ku6h4duscv9rp7j0ledvu9vrrzs6p4e3l

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/10111/229356917-d0ed4023-2930-4883-9fa2-808ebd969af7.png)

**Comment by vivganes** [comment]
As per the [readme](https://github.com/v0l/snort#snort) file, snort does not yet support [NIP-18](https://github.com/nostr-protocol/nips/blob/master/18.md) which introduces the event kind `6`, which is a repost event.

@v0l please close this issue if the above explanation is valid 👆🏽

**Comment by v0l** [comment]
We dont support replying to reposts (yet?)
