### ISSUE TITLE
Profiles are not loading

### ISSUE THREAD

**Issue by Giszmo** [v0l/snort#481]
**Describe the bug**

All over snort, I see ten ostriches with npub... for every profile picture/name.

For example when opening my chats, I see 51 npubs and only a hand full of profiles with names.

**Screenshots**

![Screenshot from 2023-04-03 14-56-50](https://user-images.githubusercontent.com/96378/229601395-1b8dd677-8248-44da-a1c3-46ec5d57b96f.png)

**Desktop (please complete the following information):**

- OS: Debian
- Browser FF
- Version 96.0.3 (64-bit)

**Comment by v0l** [comment]
Should be fixed in c51563661644c26d60ed6b3ab81ce8774a637013
