### ISSUE TITLE
New link preview not always working

### ISSUE THREAD

**Issue by callebtc** [v0l/snort#484]
**Describe the bug**
When looking at this note `nevent1qqsp9zcs938lq0zjyyvawx37cwgylkpwasr27cc00etcn9q4d67c6tsjr9kh7` I can see that snort is trying to show me something but there is nothing. :)

![image](https://user-images.githubusercontent.com/93376500/229827285-4049a88a-094e-42bc-b04b-ad2bd84d6437.png)

**Comment by vivganes** [comment]
I am ready to take and work on this @v0l 

In case title and description are not working, can we just show the card with site_name ?
