### ISSUE TITLE
Login form needs to protect privacy of the secret key

### ISSUE THREAD

**Issue by vivganes** [v0l/snort#495]
**Is your feature request related to a problem? Please describe.**
The current login form uses an ordinary unmasked text field to input the key. This doesn't protect the privacy of the user as attacker could take a picture of the screen and use it to login later.

**Describe the solution you'd like**
Use a password input field instead, optionally allowing the user to reveal the text input on demand.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Additional advantage is that password managers like bitwarden can be used to auto-fill without much hassle.

**Comment by Johnny112F** [comment]
I'm happy to work on this issue.

**Comment by vivganes** [comment]
> I'm happy to work on this issue.

I submitted PR #499 that aims to fix this issue. It is in review now. 

Happy to collaborate with you on that if you want to.

**Comment by Johnny112F** [comment]
Collaborating would be great. It looks like your fix resolved the issue well. I coded a quick solution but I think yours has passed.

**Comment by vivganes** [comment]
@Johnny112F I was planning on starting #502 today.  If you want to take it up, I will work on something else.  If you need any help, I can also help you in of any issue of your choice (including #502)
