### ISSUE TITLE
Bookmarks seem to be broken

### ISSUE THREAD

**Issue by SamSamskies** [v0l/snort#496]
**Describe the bug**
My bookmarks are not rendering anymore.

<img width="855" alt="Screenshot 2023-04-06 at 12 06 39 PM" src="https://user-images.githubusercontent.com/3655410/230460404-f4b1c1e7-97e8-470a-8eaf-3d61fdb5671f.png">

**To Reproduce**

1. Go to my profile https://snort.social/p/npub1vp8fdcyejd4pqjyrjk9sgz68vuhq7pyvnzk8j0ehlljvwgp8n6eqsrnpsw
2. Click on Bookmarks

**Comment by vivganes** [comment]
Looks like the bookmark was created for the Reaction events, Zap events, etc and not the actual TextNote event.

Submitted PR #498  to fix this

**Comment by SamSamskies** [comment]
Now all my bookmarks are gone. I'll need to investigate this more.
