### ISSUE TITLE
NIP-42 does not work [500k Bounty]

### ISSUE THREAD

**Issue by nostr-wine** [v0l/snort#520]
**Describe the bug**
It seems NIP-42 was once added to snort but no longer works. We are offering a 500k sats bounty to fix this feature. 

**To Reproduce**

1. Add a relay that requires auth (Kollider's pay relay, filter.nostr.wine with no path)
2. Try to browse global/any view
3. No content and console errors. 

**Expected behavior**
It should respond to the AUTH correctly and then re-send the REQs (poorly defined in the NIP-42 spec how to handle the "lost" REQs).

**Comment by LiranCohen** [comment]
I originally implemented NIP-42 a long while ago.

I'll try to make time this week to take a look and see what broke.

Is it just broken with this particular server? Do other NIP-42 servers respond ok?

Currently on mobile so can't debug but will def look at this week.

**Comment by nostr-wine** [comment]
The only two I know of are wss://nostr.kollider.xyz and wss://filter.nostr.wine and it does not work with either.

**Comment by nostr-wine** [comment]
Playing with this a bit more today, it seems if you select an AUTH relay in global, then select a different one, then go back to the AUTH relay, it will load events (sometimes). 

So it does seem to be working, but perhaps the flow of what happens to the REQs that were sent before/simultaneously the AUTH event is received needs to be improved. I don't expect relays to keep track of the missing state with the way the NIP is currently written.

**Comment by LiranCohen** [comment]
Ah yeah, I think I know what's going on.

When we originally implemented it the global feed did not allow you to select a specific relay.

I'm going to try to find some time and dig into how it can be fixed.

Like you said, the REQ has a race condition with AUTH.  I have some ideas but will need to find some time this week to mess with it.

**Comment by nostr-wine** [comment]
No rush, thanks for your help. We appreciate it.

**Comment by v0l** [comment]
On some of the other relays, they implemented some buffering of pending REQ messages, seems like your relay doesnt do this, any chance you could send AUTH on connect?

**Comment by nostr-wine** [comment]
We do prompt for AUTH on connect at wss://filter.nostr.wine (but we do not buffer pending REQs).

**Comment by v0l** [comment]
Ok, can you enable `auth_required` in `limitations` ?

**Comment by nostr-wine** [comment]
I can. It's a bit unclear because right now its optional (we still support using /npub if you don't use AUTH) but I will add it regardless. I don't think there is any harm. I'm on it now.

**Comment by nostr-wine** [comment]
auth_required has been flipped to "true" in limitations. 

I just want to add that we sympathize with the REQ/AUTH race condition and really wish there was some clarity in the NIP of how clients and relays are expected to address it. Using NIP-42 to do some granular limiting (like only on kind 4 REQs) will result in these same issues.

**Comment by nostr-wine** [comment]
Thank you! Bounty paid.
