### ISSUE TITLE
Account switching does not work correctly

### ISSUE THREAD

**Issue by mattn** [v0l/snort#530]
**Describe the bug**

```
An error has occured!
{}
```

**To Reproduce**

1. Go to 'https://snort.social'
2. Click on 'Logout'
3. Login with NIP-07
4. See that relay informations are empty
5. Add new relay once
6. See an error

**Expected behavior**

No errors

**Desktop (please complete the following information):**

- OS: Linux
- Browser: chrome
- Version: latest (I can't confirm because the error)

**Smartphone (please complete the following information):**

I can't repro this on mobile phone

**Additional context**

As far as I can look, relay informations are not restored with logins.

**Comment by mattn** [comment]
Hmm, it seems that this occur only with my npub. Could you please login with my npub?

npub1937vv2nf06360qn9y8el6d8sevnndy7tuh5nzre4gj05xc32tnwqauhaj6

**Comment by v0l** [comment]
I see the relays are not updating properly for other accounts, multi-account still needs a bit of work

**Comment by mattn** [comment]
I figure out why this occured.

Few weeks ago, I send DM to my self via my CLI tool. The message was broken as that kind is 4 but tags is empty. So snort raise an error when load DMs. Probably, recent changes make snort restrictly. I tried to delete the DM but wss://relay.snort.social does not behave deletion of DM with kind 5.

Could you please handle which one of two.
1. support kind 5 for DM on relay.snort.social
2. ignore broken DMs (ex: kind 4 but tags is empty)

**Comment by mattn** [comment]
Now I noticed that wss://relay.snort.social become payed relay. I can no longer log in to snort unless I delete the 4 broken DMs. please help @v0l

**Comment by mattn** [comment]
FYI, This unwrap raise an exception when the DM does not have any tags.

https://github.com/v0l/snort/blob/9258253f65583763793dae57fcc51d2f4d135a96/packages/app/src/Pages/MessagesPage.tsx#L107-L108
