### ISSUE TITLE
Where can i copy my private key?

### ISSUE THREAD

**Issue by Stosso** [v0l/snort#531]
Where can i find my private key in snort.social?
i've looked every where but couldn't find it.....

**Comment by v0l** [comment]
You should already have a copy of your private key? Snort is not the place to find your private key

**Comment by Stosso** [comment]
Thank you so much for your quick response! Unfortunately, I'm unable to find my private key... :-(

**Comment by vivganes** [comment]
> Thank you so much for your quick response! Unfortunately, I'm unable to find my private key... :-(

In case you are using a browser extension like flamingo to login to snort, you will be able to copy your private key from there. 

Also, if you are using nostr from Android using amethyst , you can copy the key from there too.

**Comment by v0l** [comment]
Implemented "Export Keys" page in settings
