### ISSUE TITLE
follow/unfollow button is not visible in Firefox

### ISSUE THREAD

**Issue by psic4t** [v0l/snort#546]
**Describe the bug**
follow/unfollow button is not visible in Firefox

**To Reproduce**

1. Go to profile/following
2. Expect "unfollow" button right to the contact name
3. Not there. :)

**Expected behavior**
See all buttons

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 112

**Comment by mdebus** [comment]
Additional info: The button has a "display: none !important;" element. Don't know, why.

I use nos2x-fox to login.

**Comment by v0l** [comment]
This is the case for `read-only` logins with npub etc
