### ISSUE TITLE
Some UI suggestions

### ISSUE THREAD

**Issue by humble-GOAT** [v0l/snort#587]
I am just exploring your app, it looks great, thank you for building it :)

I noticed a couple of small things which I consider worth bringing to your attention, because it's a part of the new user on-boarding experience. 

**Describe the bug**

As a new user with no follows, the following is presented when logging-in (chrome / linux-mint / 10 inch monitor)

![image](https://github.com/user-attachments/assets/c87d74e4-e7f1-41fb-a8cd-c8a2c151ceed)

They are minor issues but I spotted the following: 

- The 'Hmm nothing here.. ' text looks like would need a margin to the left.
- First line says 'checkout' and other line says 'check out' - they should be consistent.
- The first link ( new users page) is not underlined- probably it should be.

I hope this is helpful.

**Comment by v0l** [comment]
7b6a813c8a6d00f57179ca7742233cee6c815c16
