### ISSUE TITLE
profile page shows title starting with "npub" but shows nprofile in reality

### ISSUE THREAD

**Issue by MichiSpebach** [v0l/snort#588]
**To Reproduce**
1. Search for a name or go to a profile page where a title starting starting with "npub..." is displayed (not all profiles display this, maybe that's also a bug)
2. The string after "npub" is not the npub but the nprofile

**Expected behavior**
Either the correct npub should be displayed or the well formatted nprofile or nothing.

**Screenshots**
![image](https://github.com/user-attachments/assets/123d07e5-5c2b-4299-85c9-b266a7686140)

**Desktop**
- OS: [Windows]
- Browser: [Firefox, Chrome]
- Version: [130 (Firefox), 128 (Chrome)]

**Additional context**
Happens when started locally and also on snort.social

How should it behave?

**Comment by v0l** [comment]
npub and nprofile are the same thing
