### ISSUE TITLE
Improving displaying of newer emojis

### ISSUE THREAD

**Issue by rockstardev** [v0l/snort#62]
Example here: https://snort.social/e/note1t92zm5j3l2flkf39r4g04f8xz6x85sc0dttagw4a6gjhw5pgr8kqcvrt9q

![image](https://user-images.githubusercontent.com/5191402/212503609-7abf1dc6-c2db-440a-8ac9-4f49428223ef.png)

Compared to [hamstr.to](https://hamstr.to/thread/note1vz7e3d8dw23hewqm23wuhhk50jxag54c78s76kagkn297yx50dlqr7c6ln) for example:

![image](https://user-images.githubusercontent.com/5191402/212503640-6c1afb3b-4f51-4c9e-a8d1-2711b2e42f38.png)

**Comment by v0l** [comment]
Interesting... look ok for me on snort? 
![image](https://user-images.githubusercontent.com/1172179/212534555-375658a2-ec17-49e5-9905-8f0b5b4d067c.png)

**Comment by v0l** [comment]
You're on windows chrome @rockstardev ?

**Comment by verbiricha** [comment]
we changed font recently, you still have this issue @rockstardev ?
