### ISSUE TITLE
Suggestion: change the license to MIT

### ISSUE THREAD

**Issue by adamritter** [v0l/snort#97]
Hi guys,

I'm the developer of a RelayPool implementation for nostr: https://github.com/adamritter/nostr-relaypool-ts

Also I started developing another nostr client: https://github.com/adamritter/svelte-nostr/

I'm planning to improve the library and to maybe create more libraries that all nostr client creators may use in the future, and I think code sharing would be great between projects.

I'm not sure why GPL was selected as the license for snort, but I would suggest changing it to MIT while all authors are able to give permission (unless it was on purpose).

GPL is a copyleft license, which means that if a library code is extracted from it, it has to be GPL and can be only used by other GPL clients. I understand that Damus uses the same license, but I would prefer to have more non-copyleft code base in the community.

**Comment by v0l** [comment]
Thanks for the suggestion, i dont want to change the license, this codebase should be open source forever.

I have plans to extract the core of this site into `snort-core` repo which will contain only the nostr code and custom hooks which is what we are using to manage relays and subscriptions
