### ISSUE TITLE
Soundcloud embed

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#98]

**Comment by ivanacostarubio** [comment]
Should not render a player 
https://snort.social/e/2ee5cbc3bad838460a039cc91d7e1b01ccc26ad0f29d40978598890943798bc5 

Should render a player 
https://snort.social/e/note15c4d8yef69drhqc0vujmp5y0nvu5nkyev4v4xxp3h0qujcxqx9aqf86klu
